/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpDeleteFilled: typeof import('~icons/ep/delete-filled')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpFemale: typeof import('~icons/ep/female')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    IEpMale: typeof import('~icons/ep/male')['default']
    IEpManagement: typeof import('~icons/ep/management')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpPlatform: typeof import('~icons/ep/platform')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/svgIcon/index.vue')['default']
  }
}
